### ISSUE TITLE
Linux compile problems

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/MissionScanner#5]
I'm able to mostly compile the source code on Linux using:
```
i686-w64-mingw32-g++ -IOP2Utility/include/ -IOutpost2DLL/ -std=c++17 *.cpp -LOP2Utility/ -lOP2Utility -lstdc++fs
```

Unfortunately that results in link errors (slightly edited):
```
OP2Utility/libOP2Utility.a(XFile.o): In function `ZN5XFile6AppendERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_':
MissionScanner/OP2Utility/src/XFile.cpp:80: undefined reference to `std::experimental::filesystem::v1::__cxx11::path::generic_string() const'
OP2Utility/libOP2Utility.a(XFile.o): In function `ZN5XFile25GetFilenamesFromDirectoryERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE':
MissionScanner/OP2Utility/src/XFile.cpp:102: undefined reference to `std::experimental::filesystem::v1::__cxx11::path::generic_string() const'
OP2Utility/libOP2Utility.a(XFile.o): In function `ZN5XFile15ReplaceFilenameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_':
MissionScanner/OP2Utility/src/XFile.cpp:169: undefined reference to `std::experimental::filesystem::v1::__cxx11::path::generic_string() const'
OP2Utility/libOP2Utility.a(XFile.o): In function `ZN5XFile12GetDirectoryERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE':
MissionScanner/OP2Utility/src/XFile.cpp:218: undefined reference to `std::experimental::filesystem::v1::__cxx11::path::generic_string() const'
collect2: error: ld returned 1 exit status
```

Curiously it is a link error, not a compile error. That would suggest the function is defined in a header file, but no implementation can be found. Not sure if this is a deficiency in the `<experimental/filesystem>` library used by mingw, lacking `path::generic_string()`, or if the wrong set of libraries are being linked. For this type of error, usually it's the wrong set of libraries are being linked.

----

I wonder if updating OP2Utility to potentially use the Boost version `<boost/filesystem>` might help.

----

This project makes use of `<windows.h>` so attempts to compile with Clang and GCC didn't work. The other projects using OP2Utility (OP2Archive and OP2MapImager) don't use `<windows.h>` and are typically compiled with Clang or GCC.

**Comment by Brett208** [comment]
Mission Scanner is using a very limited subset of OP2Utility (all in XFile). If you want to make it compile via mingw, I would be okay with pulling these limited functions into MissionScanner and rewriting them to be compatible. That would eliminate the need to compile all of OP2Utility on mingw. 

I'm assuming there is no way around the windows header include since we are loading DLLs compiled for Windows.

Thanks for trying this out.

-Brett

**Comment by DanRStevens** [comment]
Funny you should mention loading the DLLs. The Windows `LoadLibrary` call is actually a bit slow. I believe for that reason, the game doesn't actually use it until a level is actually selected. Before loading a level, when the game displays a list of games, it instead manually opens each DLL, traverses the DLL header structures to find the exports, and reads the data values. This turns out to be much faster than trying to load each DLL with `LoadLibrary` and then calling `GetProcAddress`. If we did similar, the code would likely run faster, and could probably be compiled on any platform with any compiler.

From a development perspective, it would probably be easier and faster to extract portions of XFile.

Might also be interesting to work on OP2Utility to make it more robust in terms of how it can be compiled.

**Comment by Brett208** [comment]
I'm happy closing this now unless @DanRStevens  wants to tie it to actually having a makefile in the repository.

-Brett

**Comment by DanRStevens** [comment]
Yes, actually, I would like to add a Linux makefile. We can probably copy the makefile from op2ext.

This got me thinking about a couple of makefile upgrades I wanted to do in op2ext. Not sure if we want to import the makefile now, or wait until those are finished. They are:
https://github.com/OutpostUniverse/op2ext/issues/262
https://github.com/OutpostUniverse/op2ext/issues/263
