### ISSUE TITLE
Remove Outpost2DLL dependency from DllExportedVariableReader32

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/MissionScanner#9]
My goal was to make DllExportedVariableReader32 not rely on Outpost 2 specific code. DllExportedVariableReader32 needs a way to allow access to the custom data structure AIModDesc without prior knowledge to the structure's definition. 

I was wanting to add a GetObjectPointer function that would just return a pointer to the beginning of the custom structure's data. Then the user could cast the pointer into the structure of interest. I guess the pointer would be tied to the life of the copy of DllExportedVariableReader32 used to create it.

The other option would be perhaps some sort of template that ensure the struct's definition is simple enough before building it and passing it out. This seemed cleaner, but for more complex data structures, one might still need the pointer type solution anyways.

```C++
AIModDesc DllExportedVariableReader32::GetAiModDesc()
{
	stream.Seek(GetExportedFileOffset("DescBlock"));

	AIModDesc aiModDesc;
	stream.Read(aiModDesc);
	return aiModDesc;
}
```

**Comment by DanRStevens** [comment]
I kind of like your function as written. It's quite clear and easy to use.

It seems the only dependence on Outpost2DLL are the definitions of `AIModDesc` and `MissionTypes`. If you want to remove the dependence on Outpost2DLL, just copy those two definitions into their own header file and use that.

----

The template idea is interesting. By moving the method to the header and making it a template, you can delay the visibility of the structure you are reading to the translation unit of the caller. You would still need the definitions of the structs you are reading in the caller though, so it doesn't really remove the dependence on `AIModDesc`. It just limits the visibility a bit more. And course makes the code more generic and able to read other types of structs.

```cpp
// In DllExportedVariableReader32.h
template <typename StructType>
StructType DllExportedVariableReader32::GetStruct(const std::string& exportName) {
	stream.Seek(GetExportedFileOffset(exportName));

	StructType structValue;
	stream.Read(structValue);
	return structValue;
}
```

```cpp
// In caller (.cpp)
struct SomeStruct {
  // ...
};

auto structValue = exportVariableReader.GetStruct<SomeStruct>("SomeStructExport");
```

----

One issue with a raw pointer solution is the size of the pointed to data would not be automatically known. That would be an issue for the `stream.Read` call, and impose memory management issues.

One way around the size limitation is if you just loaded the whole DLL file into memory. That could be done through file reading, or more typically it would be done through memory mapping. In that case, you'd just cast the result of the memory equivalent of `GetExportedFileOffset`:
```cpp
auto SomeStruct& structValue = *reinterpret_cast<SomeStruct*>(GetExportAddress("SomeStructExport"));
```

The `reinterpret_cast` could of course be wrapped into a template method.

**Comment by Brett208** [comment]
My goal is to remove the Outpost2DLL.h include from within DllExportedVariableReader32.h/.cpp and make it more generic. I would still include Outpost2Dll.h in the rest of the project. 

This would allow lifting the reader out of MissionScanner if ever desired elsewhere with zero changes.

Thanks for laying out the template. I'll give it a shot sometime and see if I can get it to work as I don't work with templates that often.

-Brett
